name: Pages

on:
  push:
    branches:
      - gh-pages # default branch
  schedule:
    - cron: "0 */6 * * *" # 每隔6h运行一次并更新当天文章内容

  workflow_dispatch:


jobs:  # 任务列表

#--------------   v2ray    --------------#

  v2ray:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2


    - name: 复制模板
      run: |
        cp source/v2ray.md v2ray.md


    - name: curl README.md
      run: |
        curl https://raw.githubusercontent.com/xiaoji235/airport-free/refs/heads/main/README.md > tmp.txt

    - name: 提交变量<date_name>
      run: |
        DATE=$(date -u -d "+8 hours" '+%Y-%m-%d')
          sed -i "s/<date_name>/$DATE/" v2ray.md

    - name: 提交变量<time_name>
      run: |
        TIME=$(date -u -d "+8 hours" '+%Y年%m月%d日')
          sed -i "s/<time_name>/$TIME/" v2ray.md

    - name: 提交变量<posts_name>
      run: |
        cat tmp.txt >> v2ray.md
          

    - name: 重命名和删除临时文本
      run: |
        rm -f tmp.txt
        DATE=$(date -u -d "+8 hours" '+%Y-%m-%d')
        rm -f source/_posts/"$DATE".md || true
        mv v2ray.md source/_posts/"$DATE".md


    - name: Commit and push if there are changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "自动推文" && git push


#--------------   博客构建    --------------#


  build:
    needs: v2ray
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # If your repository depends on submodule, please see: https://github.com/actions/checkout
          submodules: recursive
      - name: Use Node.js 22.8.0
        uses: actions/setup-node@v4
        with:
          # Examples: 20, 18.19, >=16.20.2, lts/Iron, lts/Hydrogen, *, latest, current, node
          # Ref: https://github.com/actions/setup-node#supported-version-syntax
          node-version: "22.8.0"
      - name: Cache NPM dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        
